services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        BUILD_TYPE: production
      additional_contexts:
        gitdir: ./.git
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: antonlu/arcadia-app:latest
