"""Add camera and lens alias tables

Revision ID: 387eb86420f6
Revises: 001_initial_schema
Create Date: 2025-09-19 14:28:39.190712

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "387eb86420f6"
down_revision = "001_initial_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subapps")
    op.drop_index("ix_photos_date_taken", table_name="photos")
    op.drop_index("ix_photos_featured", table_name="photos")
    op.drop_index("ix_photos_location", table_name="photos")
    op.drop_index("ix_photos_order", table_name="photos")
    op.drop_table("photos")
    op.drop_table("users")
    op.drop_index("ix_blog_posts_published", table_name="blog_posts")
    op.drop_index("ix_blog_posts_published_at", table_name="blog_posts")
    op.drop_table("blog_posts")
    op.drop_index("idx_content_category", table_name="content")
    op.drop_index("idx_content_is_active", table_name="content")
    op.drop_table("content")
    op.drop_index("ix_projects_featured", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "short_description",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "github_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "demo_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "repository_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "repository_owner",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "repository_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("use_readme", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("readme_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "readme_last_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("technologies", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("featured", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="projects_pkey"),
        sa.UniqueConstraint(
            "slug",
            name="projects_slug_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index("ix_projects_featured", "projects", ["featured"], unique=False)
    op.create_table(
        "content",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "content_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="content_pkey"),
        sa.UniqueConstraint(
            "key",
            name="uq_content_key_value",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index("idx_content_is_active", "content", ["is_active"], unique=False)
    op.create_index("idx_content_category", "content", ["category"], unique=False)
    op.create_table(
        "blog_posts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("excerpt", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("published", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "meta_description",
            sa.VARCHAR(length=160),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "featured_image", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("tags", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("view_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("read_time", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="blog_posts_pkey"),
        sa.UniqueConstraint(
            "slug",
            name="blog_posts_slug_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        "ix_blog_posts_published_at", "blog_posts", ["published_at"], unique=False
    )
    op.create_index(
        "ix_blog_posts_published", "blog_posts", ["published"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint(
            "email",
            name="users_email_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "username",
            name="users_username_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("tags", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "original_path", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column(
            "variants",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "location_lat",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "location_lon",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "location_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column("location_address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "altitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timezone", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "camera_make", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "camera_model", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("lens", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("iso", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "aperture",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "shutter_speed", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("focal_length", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "date_taken", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "custom_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("width", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("height", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("featured", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("view_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="photos_pkey"),
    )
    op.create_index("ix_photos_order", "photos", ["order"], unique=False)
    op.create_index(
        "ix_photos_location", "photos", ["location_lat", "location_lon"], unique=False
    )
    op.create_index("ix_photos_featured", "photos", ["featured"], unique=False)
    op.create_index("ix_photos_date_taken", "photos", ["date_taken"], unique=False)
    op.create_table(
        "subapps",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("icon", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("color", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("is_external", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("requires_auth", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("admin_only", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("show_in_menu", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="subapps_pkey"),
        sa.UniqueConstraint(
            "slug",
            name="subapps_slug_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
